export const paymentMethods = [
  "m-pesa (till)",
  "m-pesa (paybill)",
  "m-pesa (send money)",
  "m-pesa (online)",
  "cash",
  "bank transfer",
  "bank standing order",
  "card (debit)",
  "card (credit)",
  "cheque",
  "pesalink",
  "airtel money",
  "equitel money",
  "t-kash",
  "paypal",
  "google pay",
  "apple pay",
];
