version: "2"

run:
  timeout: 10m

issues:
  max-issues-per-linter: 100
  max-same-issues: 100

linters:
  default: all
  disable:
    - gomodguard
  settings:
    funlen:
      lines: -1
      statements: -1
    gocritic:
      enable-all: true
    staticcheck:
      checks:
        - "all"
        - "-QF1008"
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
