version: "2"

run:
  timeout: 10m

issues:
  max-issues-per-linter: 100
  max-same-issues: 100

linters:
  default: all
  disable:
    - gomodguard
    - interfacebloat
    - wsl
    - wrapcheck
    - varnamelen
    - revive
    - recvcheck
    - ireturn
    - exhaustruct
    - err113
    - dupl
    - depguard
    - gosec
  settings:
    funlen:
      lines: -1
      statements: -1
    gocritic:
      enable-all: true
      disabled-checks:
        - hugeParam
        - whyNoLint
    staticcheck:
      checks:
        - "all"
        - "-QF1008"
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
